package com.myspace.introduction_drl;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class loanApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer age;
	private java.lang.Boolean isApproved;

	private java.lang.Integer salary;

	private java.lang.Integer requestedAmount;

	public loanApplication() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Boolean getIsApproved() {
		return this.isApproved;
	}

	public void setIsApproved(java.lang.Boolean isApproved) {
		this.isApproved = isApproved;
	}

	public java.lang.Integer getSalary() {
		return this.salary;
	}

	public void setSalary(java.lang.Integer salary) {
		this.salary = salary;
	}

	public java.lang.Integer getRequestedAmount() {
		return this.requestedAmount;
	}

	public void setRequestedAmount(java.lang.Integer requestedAmount) {
		this.requestedAmount = requestedAmount;
	}

	public loanApplication(java.lang.Integer age, java.lang.Boolean isApproved,
			java.lang.Integer salary, java.lang.Integer requestedAmount) {
		this.age = age;
		this.isApproved = isApproved;
		this.salary = salary;
		this.requestedAmount = requestedAmount;
	}

}