package com.myspace.introduction_drl;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class loanApplication implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public loanApplication() {
    }




}